services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: blockchain-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      # Configura duas portas: 29092 para os containers conversarem e 9092 para o seu Python acessar localmente
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  init-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-init
    depends_on:
      - kafka
    # Script adaptado para os comandos da imagem Confluent
    command: >
      bash -c "
        echo 'Aguardando o Kafka subir...' &&
        sleep 15 &&
        kafka-topics --create --topic cadeia-suprimentos-eventos --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 --if-not-exists &&
        kafka-topics --create --topic cadeia-suprimentos-blocos --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 --if-not-exists &&
        echo 'Tópicos criados com sucesso!'
      "
